name: Continous Image Scan Analysis
on:
  schedule:
    - cron: 00 3 */20 * *
env:
   CONTAINER_REGISTRY_URL: ${{secrets.CONTAINER_REGISTRY_URL}}
jobs:
   Assurance-Scan:
     environment: Development
     runs-on: "ubuntu-latest"
     steps:
       - name: "Scan Image"
         uses: azure/container-scan@v0
         with:
           image-name: CONTAINER_REGISTRY_URL/my-image:${{ github.sha }}
           username: ${{ secrets.REGISTRY_USERNAME }}
           password: ${{ secrets.REGISTRY_PASSWORD }}
